[package]
name = 'shelldoc'
slug = 'shelldoc'
version = '0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'An shdoc wrapper that does the heavy lifting'

[run]
dependencies = []
sourceDirs = ['pkg/lib/cmd', 'pkg/lib']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = ' on'
pipefail = 'on'

[run.shoptOptions]
extglob = 'on'
nullglob = 'on'
shift_verbose = 'on'
